services:
  rancher:
    build:
      context: ./
      dockerfile: dockerfile
    container_name: rancher
    ports:
      - "8005:8005"
      - "8080:8080"
      - "8081:8081"
    volumes:
      - ./file:/usr/app
    networks:
      - ranch
    working_dir: /usr/app/extension
    command: ["tail", "-f", "/dev/null"] # Keep the container running for debugging
    # command: ["bash", "-lc", "API=https://priv-mtsremtmcstg.prod.lan/ yarn dev"]

networks:
  ranch:
    driver: bridge